### ISSUE TITLE
对于高分辨率的贴图的转换错误

### ISSUE THREAD

**Issue by Mzhuangshao** [koimiaori/miaopacks#1]
# 错误的转换（1.21.1）
![image](https://github.com/user-attachments/assets/b87b82ef-e07b-45fd-b9d4-5c2be694cf29)
![image](https://github.com/user-attachments/assets/8e5947a9-3acd-492d-8dd2-d071d24307e4)
![image](https://github.com/user-attachments/assets/2d0d98b3-adb0-4ad3-9b85-302f5209e470)

# 原贴图（1.20.1）
![image](https://github.com/user-attachments/assets/770c145c-438c-4523-ad66-36c5e4e83843)
![image](https://github.com/user-attachments/assets/783eaeb2-083c-40c0-ae5e-c00003a2a018)

~~我不懂python所以提供不了解决方法~~

**Comment by koimiaori** [comment]
啊 现在是裁剪固定像素得到的贴图 所以会有这个bug，暂时只支持原版分辨率材质包 我看看怎么解决吧
UwU

**Comment by koimiaori** [comment]
已添加对高分辨率的支持，转换界面选择分辨率下拉框选择需要的分辨率即可。由于gui目录下world_selection.png并未改变分辨率所以需要手动放大/删除。
